services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: CHANGE_ME_TO_A_LONG_RANDOM_PASSWORD
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo-data:/data/db
  app:
    build:
      context: .
      args:
        PAYLOAD_SECRET: ${PAYLOAD_SECRET}
        DATABASE_URI: ${DATABASE_URI_INTERNAL}
        SKIP_BUILD_DB: '1'
        NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
        VERCEL_PROJECT_PRODUCTION_URL: ${VERCEL_PROJECT_PRODUCTION_URL}
    container_name: ddd-app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - .env
    environment:
      DATABASE_URI: ${DATABASE_URI_INTERNAL}
    ports:
      - '3000:3000'

volumes:
  minio-data:
  mongo-data: