services:
  app:
    build:
      context: .
      args:
        PAYLOAD_SECRET: ${PAYLOAD_SECRET}
        SKIP_BUILD_DB: '1'
        NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
        VERCEL_PROJECT_PRODUCTION_URL: ${VERCEL_PROJECT_PRODUCTION_URL}
    container_name: sebweb-app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '3000:3000'
    # depends_on:
    #   - mongodb

  # mongo:
  #   image: mongo:8
  #   container_name: mongodb
  #   volumes:
  #     - mongo-data:/data/db
  #   # optional: expose to host for Compass etc.
  #   ports:
  #     - "27017:27017"

volumes:
  mongo-data:
  # minio-data:
